version: '3.8'
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd ./services/authentication && uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DB_URI=postgresql://juliomihali:juliomihali@db:5432/usersdb?
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=juliomihali
      - POSTGRES_PASSWORD=juliomihali
      - POSTGRES_DB=usersdb