name: Tests

on:
  push:
    branches:
      - "xhulio"

  pull_request:
    branches:
      - "*"
env:
  CI: true

jobs:
  lint:
    name: Run tests

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup enviroment
        run: |
          brew install pyenv
          pyenv install 3.9.0
          make setup-env
      - name: Install dependencies and run tests
        env:
          TEST_DATABASE_HOSTNAME: localhost
          TEST_DATABASE_PASSWORD: postgres
          TEST_DATABASE_PORT: 5432
          TEST_DATABASE_USER: postgres
          TEST_DATABASE_DB: postgres
        run: |
          make migrations module=authentication name=userstable
          make test module=authentication
