name: Tests

on:
  push:
    branches:
      - "xhulio"

  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Run tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Before script
        run: |
          before_script:
            - apk update && apk add bash

      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install enviroment
        run: |
          make run module=authentication

      - name: Run Tests
        env:
          SECRET_KEY: secret_key
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
        run: |
          make test module=authentication
      - name: Format code
        run: |
          make format
