name: Tests

on:
  push:
    branches:
      - "xhulio"

  pull_request:
    branches:
      - "*"
env:
  CI: true

jobs:
  lint:
    name: Run tests

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup enviroment
        run: |
          brew install pyenv
          pyenv install 3.9.0
          make setup-env
      - name: Install dependencies and run tests
        run: |
          make test module=authentication
